# quarter 2

In [1]:
import numpy as np

In [10]:
array3d = np.arange(50).reshape(2,5,5                               )
array3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [21]:
array3d[1,2,2]

37

In [28]:
array3d[0,2:,3:]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [29]:
array3d[0,2:4,2]

array([12, 17])

In [32]:
array3d[0:,2:,3:]

array([[[13, 14],
        [18, 19],
        [23, 24]],

       [[38, 39],
        [43, 44],
        [48, 49]]])

In [ ]:
xz