In [1]:
import pandas as pd
import numpy as np

In [11]:
frame = {'Ohio':[2003,2004,2006],
        'Nevada':[2001,2002,2005],
         'NY':[2000,2007,2008]
            }

dframe= pd.DataFrame(frame ,index = ['a','b','c'])
dframe

Ohio  Nevada    NY
a  2003    2001  2000
b  2004    2002  2007
c  2006    2005  2008

In [18]:
f1 = { 'City1' : dframe['Ohio'][0:]}
f2 = {'City2' : dframe['NY'][0:]}
f1

{'City1': a    2003
 b    2004
 c    2006
 Name: Ohio, dtype: int64}

In [13]:
f1

{'City1': a    2003
 b    2004
 c    2006
 Name: Ohio, dtype: int64}

In [23]:
city1 = pd.DataFrame(f1)
city1['City2'] = pd.DataFrame(f2)
city1

City1  City2
a   2003   2000
b   2004   2007
c   2006   2008

In [16]:
city1.values

array([[2003],
       [2004],
       [2006]], dtype=int64)

In [31]:
obj = pd.Series(['Blue','Red','Pruple','Orange'],index=[2,5,6,7])
obj

2      Blue
5       Red
6    Pruple
7    Orange
dtype: object

In [32]:
obj.reindex(range(10),method="bfill")

0      Blue
1      Blue
2      Blue
3       Red
4       Red
5       Red
6    Pruple
7    Orange
8       NaN
9       NaN
dtype: object

In [33]:
obj.reindex(range(10),method="ffill")

0       NaN
1       NaN
2      Blue
3      Blue
4      Blue
5       Red
6    Pruple
7    Orange
8    Orange
9    Orange
dtype: object

In [38]:
obj1 = pd.DataFrame(np.arange(9).reshape((3,3)),
        index = ['a','b','c'],
        columns= ['City1','City2','City3'])
obj1

City1  City2  City3
a      0      1      2
b      3      4      5
c      6      7      8

In [39]:
obj1 = obj1.drop('a')

In [40]:
obj1

City1  City2  City3
b      3      4      5
c      6      7      8

In [45]:
obj1= pd.DataFrame([0,1,2],index= "a")

TypeError: Index(...) must be called with a collection of some kind, 'a' was passed

In [44]:
obj1

City1  City2  City3   a
b      3      4      5 NaN
c      6      7      8 NaN

In [54]:
obj1


City1  City2  City3   a
b      3      4      5 NaN
c      6      7      8 NaN

In [57]:
obj1

City1  City2  City3   a
b      3      4      5 NaN
c      6      7      8 NaN

In [65]:
obj1[]

City1  City2  City3   a
b    NaN    NaN    NaN NaN
c    NaN    7.0    8.0 NaN

In [66]:
obj1['a'] = 5

In [67]:
obj1

City1  City2  City3  a
b      3      4      5  5
c      6      7      8  5

In [12]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
  index=['Ohio', 'Colorado', 'Utah', 'New York'],
  columns=['one', 'two', 'three', 'four'])

In [69]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [70]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [75]:
data[data['one']>2]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
 data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [77]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [13]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [85]:
data.iloc[:, :2][data.three > 5]

one  two
Colorado    4    5
Utah        8    9
New York   12   13

In [80]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [82]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [86]:
 ser[:1]

0    0.0
dtype: float64

In [87]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [88]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [89]:
ser.iloc[:1]

0    0.0
dtype: float64

# Query Here

In [90]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [91]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [92]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],index=['a', 'c', 'e', 'f', 'g'])

In [93]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [94]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [96]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),index=['Ohio', 'Texas', 'Colorado'])

In [97]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [98]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [99]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [5]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
arr[0]

array([0, 1, 2, 3])

In [8]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

# Lambda Function 

In [9]:
f = lambda x : x*100
f(2)

200

In [10]:
data

NameError: name 'data' is not defined

In [15]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [24]:
f = lambda x: x.max() -x.min()
data.apply(f)

one      12
two      12
three    12
four     12
dtype: int64

In [25]:
data.apply(f,axis='columns')

Ohio        3
Colorado    3
Utah        3
New York    3
dtype: int64

In [3]:
obj12 = pd.Series( range(4),index = ['a','b','c','d'])
obj12

a    0
b    1
c    2
d    3
dtype: int64

# Sortign

In [4]:
obj12.sort_index()

a    0
b    1
c    2
d    3
dtype: int64

In [5]:
frame12 = pd.DataFrame({'b' : [4,7,-3,2],'a' :[0,1,2,3]})
frame12

b  a
0  4  0
1  7  1
2 -3  2
3  2  3

In [6]:
frame12.sort_values(by=['a','b'])

b  a
0  4  0
1  7  1
2 -3  2
3  2  3

In [9]:
frame12.sort_index()

b  a
0  4  0
1  7  1
2 -3  2
3  2  3

In [15]:
obj = pd.Series([7, -5, 6, 4, 2, 0, 4])
obj

0    7
1   -5
2    6
3    4
4    2
5    0
6    4
dtype: int64

In [16]:
obj.rank()

0    7.0
1    1.0
2    6.0
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [26]:
obj11 = pd.DataFrame({'a' : [2,0],'b' :[0,2]})
obj11

a  b
0  2  0
1  0  2

In [27]:
obj11.corr()

a    b
a  1.0 -1.0
b -1.0  1.0

In [29]:
import pandas_datareader as web

In [30]:
all_data = {}
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']:
 all_data[ticker] = web.get_data_yahoo(ticker, '1/1/2000', '1/1/2010')
price = DataFrame({tic: data['Adj Close']
 for tic, data in all_data.iteritems()})
volume = DataFrame({tic: data['Volume']
 for tic, data in all_data.iteritems()})

NameError: name 'DataFrame' is not defined

In [ ]:
 returns = price.pct_change()
    returns.tail()

In [ ]:
returns.tail()